#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#	mail
#  in order to use this copy it into ./git/hooks directory of your project

echo -e "Pre-commit-hook caller\n\n"
powershell.exe -ExecutionPolicy Unrestricted -File 'SecretCheck\pre-commit.ps1'
