//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubMinimizerTests.GetResourcesServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GetResourcesServiceReference.IGetResourcesService")]
    public interface IGetResourcesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetResourcesService/GetResources", ReplyAction="http://tempuri.org/IGetResourcesService/GetResourcesResponse")]
        CogsMinimizer.Shared.Resource[] GetResources(string subscriptionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetResourcesService/GetResources", ReplyAction="http://tempuri.org/IGetResourcesService/GetResourcesResponse")]
        System.Threading.Tasks.Task<CogsMinimizer.Shared.Resource[]> GetResourcesAsync(string subscriptionID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGetResourcesServiceChannel : SubMinimizerTests.GetResourcesServiceReference.IGetResourcesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetResourcesServiceClient : System.ServiceModel.ClientBase<SubMinimizerTests.GetResourcesServiceReference.IGetResourcesService>, SubMinimizerTests.GetResourcesServiceReference.IGetResourcesService {
        
        public GetResourcesServiceClient() {
        }
        
        public GetResourcesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetResourcesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetResourcesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetResourcesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CogsMinimizer.Shared.Resource[] GetResources(string subscriptionID) {
            return base.Channel.GetResources(subscriptionID);
        }
        
        public System.Threading.Tasks.Task<CogsMinimizer.Shared.Resource[]> GetResourcesAsync(string subscriptionID) {
            return base.Channel.GetResourcesAsync(subscriptionID);
        }
    }
}
