//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CogsMinimizer.Shared
{
    using System;
    
    public enum SubscriptionManagementLevel : int
    {
        ReportOnly = 0,
        AutomaticDelete = 1,
        ManualDelete = 2
    }
}
