//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CogsMinimizer.Shared
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subscription()
        {
            this.ReserveIntervalInDays = 180;
            this.ExpirationIntervalInDays = 30;
            this.ExpirationUnclaimedIntervalInDays = 10;
            this.DeleteIntervalInDays = 7;
            this.SendEmailToCoAdmins = true;
            this.SendEmailOnlyInvalidResources = true;
        }
    
        public bool IsConnected { get; set; }
        public string DisplayName { get; set; }
        public string Id { get; set; }
        public string OrganizationId { get; set; }
        public System.DateTime ConnectedOn { get; set; }
        public string ConnectedBy { get; set; }
        public bool AzureAccessNeedsToBeRepaired { get; set; }
        public System.DateTime LastAnalysisDate { get; set; }
        public int ReserveIntervalInDays { get; set; }
        public int ExpirationIntervalInDays { get; set; }
        public int ExpirationUnclaimedIntervalInDays { get; set; }
        public int DeleteIntervalInDays { get; set; }
        public SubscriptionManagementLevel ManagementLevel { get; set; }
        public bool SendEmailToCoAdmins { get; set; }
        public bool SendEmailOnlyInvalidResources { get; set; }
    }
}
